export default {
  SELECTED: 'SELECTED',
  ADD_RECENT: 'ADD_RECENT',

  SIGNUP: 'SIGNUP',
  SIGNUP_DONE: 'SIGNUP_DONE',

  LOGIN: 'LOGIN',
  LOGIN_DONE: 'LOGIN_DONE',

  EDIT_PROFILE: 'EDIT_PROFILE',
  EDIT_PROFILE_DONE: 'EDIT_PROFILE_DONE',

  SEND_PASSWORD_LINK: 'SEND_PASSWORD_LINK',
  SEND_PASSWORD_LINK_DONE: 'SEND_PASSWORD_LINK_DONE',

  VERIFY_TOKEN: 'VERIFY_TOKEN',
  VERIFY_TOKEN_DONE: 'VERIFY_TOKEN_DONE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_DONE: 'RESET_PASSWORD_DONE',

  LOGOUT: 'LOGOUT',

  GET_LISTING: 'GET_LISTING',
  GET_LISTING_DONE: 'GET_LISTING_DONE',

  GET_GROUPS: 'GET_GROUPS',
  GET_GROUPS_DONE: 'GET_GROUPS_DONE',

  RENDER_PRODUCT: 'RENDER_PRODUCT',
  RENDER_PRODUCT_DONE: 'RENDER_PRODUCT_DONE',

  // ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  GET_WISHLIST: 'GET_WISHLIST',
  GET_WISHLIST_DONE: 'GET_WISHLIST_DONE',

  RENDER_DETAILS: 'RENDER_DETAILS',
  RENDER_DETAILS_DONE: 'RENDER_DETAILS_DONE',

  CONTACT_US: 'CONTACT_US',
  CONTACT_US_DONE: 'CONTACT_US_DONE',

  CREATE_GROUP: 'CREATE_GROUP',
  CREATE_GROUP_DONE: 'CREATE_GROUP_DONE',

  CREATE_LISTING: 'CREATE_LISTING',
  CREATE_LISTING_DONE: 'CREATE_LISTING_DONE',

  GET_REVIEWS: 'GET_REVIEWS',
  GET_REVIEWS_DONE: 'GET_REVIEWS_DONE',

  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_NOTIFICATIONS_DONE: 'GET_NOTIFICATIONS_DONE',

  PLAYERS_FOLLOW: 'PLAYERS_FOLLOW',
  PLAYERS_FOLLOW_DONE: 'PLAYERS_FOLLOW_DONE',

  GET_AREA_CODES: 'GET_AREA_CODES',

  GROUPS_BY_AREACODE: 'GROUPS_BY_AREACODE',
  GROUPS_BY_AREACODE_DONE: 'GROUPS_BY_AREACODE_DONE',

  LISTINGS_BY_AREACODE: 'LISTINGS_BY_AREACODE',
  LISTINGS_BY_AREACODE_DONE: 'LISTINGS_BY_AREACODE_DONE',

  GET_MY_GROUPS: 'GET_MY_GROUPS',
  GET_MY_GROUPS_DONE: 'GET_MY_GROUPS_DONE',

  GET_MY_LISTINGS: 'GET_MY_LISTINGS',
  GET_MY_LISTINGS_DONE: 'GET_MY_LISTINGS_DONE',

  JOIN_LISTING: 'JOIN_LISTING',
  JOIN_LISTING_DONE: 'JOIN_LISTING_DONE',

  JOIN_GROUP: 'JOIN_GROUP',
  JOIN_GROUP_DONE: 'JOIN_GROUP_DONE',

  ACCEPT_REQUEST: 'ACCEPT_GROUP',
  ACCEPT_REQUEST_DONE: 'ACCEPT_REQUEST_DONE',

  REJECT_REQUEST: 'REJECT_REQUEST',
  REJECT_REQUEST_DONE: 'REJECT_REQUEST_DONE',

  GET_ABOUT: 'GET_ABOUT',
  GET_ABOUT_DONE: 'GET_ABOUT_DONE',

  DELETE_GROUP: 'DELETE_GROUP',
  DELETE_GROUP_DONE: 'DELETE_GROUP_DONE',

  DELETE_LISTING: 'DELETE_LISTING',
  DELETE_LISTING_DONE: 'DELETE_LISTING_DONE',

  EDIT_LISTING: 'EDIT_LISTING',
  EDIT_LISTING_DONE: 'EDIT_LISTING_DONE',

  EDIT_GROUP: 'EDIT_GROUP',
  EDIT_GROUP_DONE: 'EDIT_GROUP_DONE',

  FETCH_GROUP_MEMBERS: 'FETCH_GROUP_MEMBERS',
  FETCH_LISTING_MEMBERS: 'FETCH_LISTING_MEMBERS',

  DEACTIVATE_ACCOUNT: 'DEACTIVATE_ACCOUNT',

  LISTING_STATUS: 'LISTING_STATUS',
  LISTING_STATUS_DONE: 'LISTING_STATUS_DONE',

  GROUP_STATUS: 'GROUP_STATUS',
  GROUP_STATUS_DONE: 'GROUP_STATUS_DONE'
};

export const URL = 'https://inthecup.golf/wp-json/app/v1';
