export default {
    'SELECTED': 'SELECTED',
    'ADD_RECENT': 'ADD_RECENT',

    SIGNUP: 'SIGNUP',
    SIGNUP_DONE: 'SIGNUP_DONE',

    LOGIN: 'LOGIN',
    LOGIN_DONE: 'LOGIN_DONE',

    EDIT_PROFILE: 'EDIT_PROFILE',
    EDIT_PROFILE_DONE: 'EDIT_PROFILE_DONE',

    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_DONE: 'RESET_PASSWORD_DONE',

    LOGOUT: 'LOGOUT',

    GET_LISTING: 'GET_LISTING',
    GET_LISTING_DONE: 'GET_LISTING_DONE',

    GET_GROUPS: 'GET_GROUPS',
    GET_GROUPS_DONE: 'GET_GROUPS_DONE'

}